# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e74bd8cb5b654f36405441646e13b18ab5c188afd4d0908163ac83cadfebfd142414de1a0e59301b23878cdc7c05b6cf45220327b397fccc7c59754397b75c46

test:
  secret_key_base: e9d7e67d5316cd25917b9f234990e16c09e4c16635ca93ccf23a2321b49c6b5cfd66fafc5e0ee92f959a373fb795acb62cbd98a3bc109c6a828c1dab53c6f53e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
